version: "1.0"
info:
  model: int-scaffold
packages:
- name: Sourabhghsis071026Project
  gitServerName: srcCtrl_github_Sourabh_shared2
  gitUrl: https://github.com/sourabh-harkawat-0058QC744
  gitUsername: sourabh-harkawat-0058QC744
  gitBranch: main
- name: LowerFSPackage
  gitServerName: srcCtrl_github_Sourabh_shared2
  gitUrl: https://github.com/sourabh-harkawat-0058QC744
  gitUsername: sourabh-harkawat-0058QC744
  gitBranch: testbranch
